import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Client } from '@notionhq/client'
import Link from 'next/link'

import type { Page, TitlePropertyValue } from '@notionhq/client/build/src/api-types'
import type { GetStaticProps } from 'next'

const notion = new Client({
  auth: process.env.NOTION_TOKEN,
});

export const getStaticProps: GetStaticProps = async ({ params }) =>  {
  let response = await notion.databases.query({
    database_id: 'b66f3740-ab1e-425b-a321-a806febd5f71'
  })
  return {
    props: {
      pages: response.results
    },
    revalidate: 5
  }
}

export default function Home({ pages }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {pages.map((page: Page) => {
            let pageNameProp = page.properties['Name'] as TitlePropertyValue
            let title = pageNameProp.title.map(meta => meta.plain_text)[0] ?? 'Untitled'
            return <li key={page.id}>
              <Link href={`/page/${encodeURIComponent(page.id)}`}><a>{title}</a></Link>
            </li>
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
