import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { retrievePages } from 'components/notion'
import { extractPageTitle } from 'components/notion-helper'

import type { GetStaticProps } from 'next'
import type { Page } from 'components/notion'

export const getStaticProps: GetStaticProps = async ({ params }) =>  {
  let pages = await retrievePages()
  return {
    props: {
      pages: pages
    },
    revalidate: 5
  }
}

export default function Home({ pages }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {pages.map((page: Page) => {
            let title = extractPageTitle(page)
            return <li key={page.id}>
              <Link href={`/page/${encodeURIComponent(page.id)}`}><a>{title}</a></Link>
            </li>
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
